[project]
name = "fon-aios-prefect"
version = "0.1.0"
description = "FON AIOS Prefect Implementation"
requires-python = ">=3.9"

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]
