fon_aios:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow_password
      port: 5432
      dbname: airflow_db
      schema: fon_aios
      threads: 4
      keepalives_idle: 0
