# automations/embeddings_trigger.yaml
name: trigger-embeddings-after-ingestion
description: Process embeddings after NewsAPI ingestion completes
enabled: true

trigger:
  type: event
  expect:
    - "prefect.flow-run.Completed"
  match_related:
    prefect.resource.name: "NewsAPI.ai Single Topic Test"
  posture: Reactive
  threshold: 1
  within: 60

actions:
  - type: run-deployment
    deployment:
      name: embeddings-processing
      parameters:
        parquet_path: "{{ event.resource.result.parquet_path }}"